#!/usr/bin/env bash

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset

# Turn on traces, useful while debugging but commented out by default
#set -o xtrace

BATTERY_PATH=$(upower -e | grep 'BAT0')
mapfile -t BATTERY_FIELDS < <(upower -i "${BATTERY_PATH}" | grep -E "percentage|capacity" | cut -d':' -f2 | tr -d '[:blank:]|%')

if [[ ${BATTERY_FIELDS[0]} -lt 25 ]]; then
  printf "\xEF\x89\x84 %s" "${BATTERY_FIELDS[0]}"
elif [[ ${BATTERY_FIELDS[0]} -lt 50 ]]; then
  printf "\xEF\x89\x83 %s" "${BATTERY_FIELDS[0]}"
elif [[ ${BATTERY_FIELDS[0]} -lt 75 ]]; then
  printf "\xEF\x89\x82 %s" "${BATTERY_FIELDS[0]}"
elif [[ ${BATTERY_FIELDS[0]} -lt 100 ]]; then
  printf "\xEF\x89\x81 %s" "${BATTERY_FIELDS[0]}"
else
  printf "\xEF\x89\x80 %s" "${BATTERY_FIELDS[0]}"
fi

printf " \xEF\x8A\x95 %s" "${BATTERY_FIELDS[1]}"

