#!/usr/bin/env bash

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset

# Turn on traces, useful while debugging but commented out by default
#set -o xtrace

DATE_AND_TIME=$(date "+%a %d %b %H:%M:%S")

printf "%s" "${DATE_AND_TIME}"
