#!/usr/bin/env bash

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset

# Turn on traces, useful while debugging but commented out by default
#set -o xtrace

LAYOUT_MASK=$(localectl status | grep 'X11' | cut -d':' -f2 | tr -d '[:blank:]' | tr "[:lower:]" "[:upper:]")

printf "%s" "${LAYOUT_MASK}"
